digestproj/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin

admin.autodiscover()
urlpatterns = patterns('',
    (r'^$', 'digest.views.index'),
    (r'^newfeed/$', TemplateView.as_view(template_name='digest/setup.html')),
    (r'^edit_feed/(?P<fid>\d+)/(?P<token>[a-zA-Z]{49})/', 'digest.views.edit_feed'),
    (r'^register/$', 'digest.views.register'),
    (r'^passthrough/$', 'digest.views.passthrough'),
    (r'^subscribe/$', 'digest.views.handle_subscription'),
    (r'^booky.js/$', 'digest.views.booky'),
    # Examples:
    # url(r'^$', 'digestproj2.views.home', name='home'),
    # url(r'^digestproj2/', include('digestproj2.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

digest/models.py
from datetime import datetime, timedelta
from random import randint, choice
import urllib2
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.core.mail import send_mail
from django.conf import settings
from django.forms import ModelForm
from lxml.html import fromstring

EMAIL_SUBJECT = settings.REG_EMAIL_TITLE
EMAIL_MESSAGE = settings.REG_EMAIL_MESSAGE
EMAIL_SENDER = settings.REG_EMAIL_SENDER

CHAR_CHOICES = [chr(derp) for derp in range(97,123) + range(65,91)]  # Lower and uppercase

# Not using now, but let's keep for the future
class FeedUser(AbstractBaseUser):
    email = models.EmailField(max_length=75, unique=True, db_index=True)
    USERNAME_FIELD = 'email'

    verified = models.BooleanField(default=False)
    verification_token = models.CharField(max_length=50,
        default=lambda:''.join([chr(randint(97,122)) for k in range(49)]))

    last_email_sent = models.DateTimeField(auto_now_add=True, db_index=True)

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.get_full_name()

    def send_confirmation_email(self, host='digest.seanroth.com'):
        message = EMAIL_MESSAGE.replace('{host}', host)\
            .replace('{regtoken}', self.verification_token)

        send_mail(EMAIL_SUBJECT, message, EMAIL_SENDER, (self.email,))

class Feed(models.Model):
    title = models.TextField(blank=True)
    url = models.URLField(max_length=255)
    created = models.DateTimeField(auto_now_add=True, blank=True)
    last_crawled = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    next_email = models.DateTimeField(blank=True, null=True,
                                      default=lambda: datetime.now() + timedelta(days=1))
    email_interval = models.IntegerField(null=True)  # Time between emails in seconds
    email = models.EmailField()
    #owner = models.ForeignKey(FeedUser)
    xpaths = models.TextField()
    max_amount = models.IntegerField(default=10)
    enabled = models.BooleanField(default=True)
    # Technically not unique, just random
    unique_token = models.CharField(max_length=50, blank=True)

    def get(self, key):
        return getattr(self, key)

    def get_parsed(self):
        opener = urllib2.build_opener()
        opener.addheaders = [('User-agent', ' Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:21.0) Gecko/20100101 Firefox/21.0')]
        response = opener.open(self.url)
        parsed = fromstring(response.read())
        response.close()
        return parsed

    def __unicode__(self):
        if self.title:
            return self.title
        else:
            return self.url

    def get_absolute_url(self):
        return '/edit_feed/%d/%s/' % (self.pk, self.unique_token)

    def refresh_token(self):
        # Creates string of random upper and lowercase letters
        # For some reason choice() is extremely efficient: this code is 2x
        # faster than the original lowercase implementation.
        # Originally I had choice([randint(97,122),randint(65,90)]),
        # which turned out to be more than 2x SLOWER than original
        #
        # ==Original Lowercase Only==
        # >>> timeit("''.join([chr(randint(97,122)) for k in range(49)])", number=100000, setup="from random import randint, choice")
        # 5.713801860809326
        #
        # ==First try Mixed Case==
        # >>> timeit("''.join([chr(choice([randint(97,122),randint(65,90)])) for k in range(49)])", number=100000, setup="from random import randint, choice")
        # 12.872645854949951
        #
        # ==Good===
        # >>> timeit("''.join([chr(choice(choices)) for k in range(49)])", number=100000, setup="from random import randint, choice;choices=range(97,123)+range(65,91)")
        # 2.4448201656341553
        #
        # ==Great==
        # >>> timeit("''.join([choice(choices) for k in range(49)])", number=100000, setup="from random import randint, choice;choices=[chr(derp) for derp in range(65,91)+range(97,123)]")
        # 2.1216399669647217

        self.unique_token = ''.join([choice(CHAR_CHOICES) for k in range(49)])
        return self.unique_token

    def set_interval_days(self, days):
        self.email_interval = days * 86400

    def get_interval_days(self):
        if self.email_interval:
            return self.email_interval / 86400
        else:
            return None

    def save(self, *args, **kwargs):
        if self.pk is None:  # Happens when this is a new feed
            self.refresh_token()
        super(Feed, self).save(*args, **kwargs)


class FeedItem(models.Model):
    title = models.TextField()
    url = models.URLField(max_length=500)
    created = models.DateTimeField(auto_now_add=True, blank=True)
    feed = models.ForeignKey(Feed)
    xpath = models.TextField()
    score = models.IntegerField(default=0)  # By default is length of time on website, but can be score for
                                   # sites like reddit, news.ycombinator.com, etc.
    last_active = models.DateTimeField(default=datetime.now())  # As far as we know, is this item still on the website?
    #dead = models.BooleanField(default=False)


    def __unicode__(self):
        return self.title

digest/forms.py
from django import forms

class EditFeedForm(forms.Form):
    email = forms.EmailField(label="Your email")
    title = forms.CharField()
    url = forms.URLField(label="URL")
    starting = forms.DateField(label="Date of next digest email", help_text="(mm/dd/yyyy) or (yyyy/mm/dd)")
    days_interval = forms.IntegerField(label="How many days between each digest?")
    max_amount = forms.IntegerField(label="Maximum number of items per email")
    enabled = forms.BooleanField(required=False)

digest/views.py
import urllib2, re, json
from hashlib import md5
from urlparse import urljoin
from lxml.html import fromstring, tostring
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.views.decorators.csrf import csrf_exempt

from models import FeedUser, Feed, FeedItem
from forms import EditFeedForm

def linkrepl(match):
    relative_url = match.group(1)
    return '"'

def index(request):
    return render(request, 'digest/index.html', {'host':request.get_host()})

def booky(request):
    response = render(request, 'digest/booky.js', {'host':request.get_host()})
    response['Access-Control-Allow-Origin'] = '*'
    response["Access-Control-Allow-Methods"] = "POST, GET, OPTIONS"
    response["Access-Control-Max-Age"] = "1000"
    response["Access-Control-Allow-Headers"] = "*"
    return response


def passthrough(request):
    url = request.GET['url']
    response = urllib2.urlopen(url)
    html = response.read()
    response.close()

    doc = fromstring(html)
    doc.make_links_absolute(url)
    return HttpResponse(tostring(doc))
    # Replace relative urls as best we can
    base_url = '/'.join(url.split('/')[:3])  # for links that use /something.gif
    base_url_relative = '/'.join(url.split('/')[:-1])  # for links that use something.gif
    print base_url_relative
    #rel_links = re.findall(r"(?:href|src)\s?=(['\"])((?!http).*?)\1", html)
    replaced = re.sub(r"(href|src)\s?=\s?(?P<quote>['\"])?([0-9a-zA-Z$-_.+!*(),]+)(?P=quote)",
                      "\1=\"\2\"", html)
    replaced = re.sub(r"(?P<first>(?:href|src)\s?(?P<quote>['\"]=|=))(?P<last>/((?!http).+?)(?P=quote))",
                      r"\g<first>%s\g<last>" % base_url, replaced)
    replaced = re.sub(r"(?P<first>(?:href|src)\s?(?P<quote>['\"]=|=))(?P<last>((?!http).+?)(?P=quote))",
                      r"\g<first>"+base_url_relative+r"/\g<last>", replaced)
    #linkrepl = lambda m: '"%s/%s"' % (base_url, m[1])

    return HttpResponse(replaced)

@csrf_exempt
def handle_subscription(request):
    #hierarchy = json.loads(request.POST['hierarchy'])
    #response = urllib2.urlopen(request.POST['url'])
    try:
        link_objs = json.loads(request.POST['links'])
    except ValueError:
        print request.POST['links']
        raise
    content = request.POST['cont']
    url = request.POST['url']  # TODO: Use form for this. This makes me feel dirty.

    parsed = fromstring(content)
    parsed.make_links_absolute(base_url=url)
    new_f = Feed(url=url, title=parsed.find(".//title").text)  # TODO: See above. :'(
    parsed_ours = new_f.get_parsed()
    parsed_ours.make_links_absolute(base_url=url)
    new_f.save()
    xpaths = []
    for link_obj in link_objs:
        link_obj['href'] = urljoin(url, link_obj['href'])
        feed_item = FeedItem(title=link_obj['txt'].strip(),
                             url=link_obj['href'],
                             score=0,
                             feed=new_f)
        elements = parsed.xpath(link_obj['xpath'])
        element = None
        for el in elements:
            if 'comeuppance' in el.attrib.get('class','') and link_obj.get('class','') in el.attrib.get('class','') \
                    and link_obj['txt'] == el.text and link_obj['href'] == el.attrib.get('href'):
                element = el
                break
        if element is None:
            print "returning early"
            return HttpResponse('ERROR', content_type='text/plain')

        feed_item.xpath = element.getroottree().getpath(element)  # Real xpath
        our_els = parsed_ours.xpath(feed_item.xpath)
        if not our_els:  # Means they have a different structure for browsers and spiders
            our_els = parsed_ours.find(".//a[@href='%s']" % link_obj['href'])
            if our_els:
                feed_item.xpath = our_els.getroottree().getpath(our_els)
            else:
                feed_item.xpath = ''
        if feed_item.xpath:
            xpaths.append(feed_item.xpath)
            feed_item.save()
    new_f.xpaths = ',|&'.join(xpaths)  # God help the soul that uses ,|& in an HTML id
    new_f.save()
    response = HttpResponse('%d/%s'%(new_f.id,new_f.unique_token), content_type='text/plain')
    response['Access-Control-Allow-Origin'] = '*'
    response["Access-Control-Allow-Methods"] = "POST, GET, OPTIONS"
    response["Access-Control-Max-Age"] = "1000"
    response["Access-Control-Allow-Headers"] = "*"
    return response


    tree = fromstring(page)
    print tree.getpath()
    print(tree)

    current_heirarchy_node = hierarchy
    current_tree_node = tree

    while current_heirarchy_node:
        candidate_next_nodes = current_tree_node.getchildren()
        current_tree_node = candidate_next_nodes[current_heirarchy_node['index']]
        current_heirarchy_node = current_heirarchy_node['child']
        '''
        candidate_next_nodes = filter(lambda x: x.tag == current_heirarchy_node['tag'])
        if current_heirarchy_node['id']:
            candidate_next_nodes = filter(lambda x: x.tag == current_heirarchy_node['tag'])
        '''

    print current_tree_node

    response = HttpResponse(current_tree_node.text)
    response['Access-Control-Allow-Origin'] = '*'

    return response


def edit_feed(request, fid, token=''):
    fid = int(fid)
    if not Feed.objects.filter(pk=fid, unique_token=token):
        raise Http404
    # If we've gotten this far the user is allowed to edit this feed
    feed = Feed.objects.get(pk=fid)
    if 'delete' in request.GET:
        feed.delete()
        return HttpResponse('DONE', content_type='text/plain')
    if request.method == 'POST':
        form = EditFeedForm(request.POST)
        #form.starting.label = 'Herps'
        if form.is_valid():
            feed.next_email = form.cleaned_data['starting']
            feed.set_interval_days(form.cleaned_data['days_interval'])
            feed.title = form.cleaned_data['title']
            feed.email = form.cleaned_data['email']
            feed.enabled = form.cleaned_data['enabled']
            feed.max_amount = form.cleaned_data['max_amount']
            feed.refresh_token()
            feed.save()
            return redirect('digest.views.edit_feed', fid, feed.unique_token)
    else:
        interval = feed.email_interval/86400 if feed.email_interval else None
        form = EditFeedForm(initial={'url':feed.url, 'title':feed.title, 'email':feed.email,
                                     'starting':feed.next_email,
                                     'days_interval':interval,
                                     'max_amount':feed.max_amount,
                                     'enabled':feed.enabled})

    items = feed.feeditem_set.all()
    return render(request, 'digest/edit_feed.html', {'form':form, 'links':items})

# Will use in future, for now we're using a userless approach
def register(request):
    state = 'unregistered'
    error_message = ''

    if request.method == 'POST':
        if not re.match(r'.+@\w+\.\w+', request.POST['email']):
            state = 'error'
            error_message = 'Email address not valid.'
            print request.POST['email']

        elif len(request.POST['password']) < 4:
            state = 'error'
            error_message = 'Password to short'
            print 'laa'

        else:
            new_user = FeedUser(email=request.POST['email'])
            new_user.set_password(request.POST['password'])
            new_user.save()
            print new_user.email
            new_user.send_confirmation_email()

            state = 'registered'


    return render(request, 'digest/register.html', 
        {'state':state, 'error_message':error_message} )

templates/digest/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Dijest{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
    <style>
      @media(min-width: 980px) {
        body {
          padding-top: 60px;
          padding-bottom: 40px;
        }
      }
    </style>
    {% block css %}
    {% endblock %}

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="/static/js/html5shiv.js"></script>
    <![endif]-->


    <link rel="shortcut icon" href="/static/ico/favicon.png">

  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Dijest</a>
          <!-- Below commented out until we have some actual links LOL -->
          <!--<div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>
          </div>-->
          <!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      {% block content%}
      {% endblock %}

      <hr>
      <footer>
        <p>&copy; Sean Roth & Ryan Jenkins 2013 (An SFSU CSC 697 project)</p>
      </footer>
    </div>
    <script src="/static/js/jquery.js"></script>
    {% block js %}
    {% endblock %}
  </body>
</html>

templates/digest/edit_feed.html
{% extends "digest/base.html" %}
{% block title %}Edit Feed{% endblock %}
{% block css %}
<style type="text/css">
  .invis {display:none}
</style>
{% endblock %}
{% block content %}
<div class="row">
  <div class="span6">
    <h1>Edit digest</h1>
    <div class="alert">
      <strong>Warning! Add sean@seanroth.com to your address book</strong>, otherwise your email provider might classify your digest as spam!
    </div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class="btn btn-primary" value="Submit" /> <button class="btn btn-danger" id="delete">Delete digest</button>
    </form>
  </div>
  <div class="span6">
    <div class="well">
      <h2>Preview</h2>
      <ol>
      {% for link in links %}
        <li>
        <a href="{{ link.url }}">{{ link.title }}</a>
        </li>
      {% endfor %}
      </ol>
    </div>
  </div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
function refresh_list() {
  var number = 0;
  var max_val = parseInt($("#id_max_amount").val());
  $("div div div ol li").each(function(){
    if(number >= max_val) {
      $(this).addClass('invis');
    } else {
      number++;
      $(this).removeClass('invis');
    }
  });
}
$("form").bind("keyup", refresh_list);
$("#delete").click(function() {
  $.post('?delete', {'csrfmiddlewaretoken':$("[name='csrfmiddlewaretoken']").val()}, function() {
    $("#delete").after(" <strong>Successfully deleted digest!</strong>");
  });
  return false;
});
refresh_list();
</script>
{% endblock %}

templates/digest/index.html
{% extends "digest/base.html" %}
{% block title %}Welcome to Dijest{% endblock %}
{% block css %}
<style type="text/css">
  #homeinput {
    height: 30px;
    font-size: 17.5px;
    -webkit-border-radius: 6px;
    -moz-border-radius: 6px;
    border-radius: 6px;
    margin-bottom: 0px;
    width: 25em;
  }

  #link_selection_frame {
    width: 100%;
    height: 600px;
  }
</style>
{% endblock %}

{% block js %}
<script>
  var iFD;

  function pload(url) {
    $('#loading').text('Loading...');
    // Rewrite url to include http schema if it isn't already there
    if (!url.match(/https?:\/\/.+/)) url = 'http://' + url
      
    iFD.contentDocument.location.href = '/passthrough?url=' + url;

    // Poll for the iframe to be ready. It's retarded we can't do this with an event
    (function pollFrameReady() {
      // Watch ready state here because god only knows when the iframe unloads
      if (iFD.contentDocument.readyState === 'interactive') {
        $('#loading').text('');
        var my_script = iFD.contentDocument.createElement('script');
        my_script.type='text/javascript';
        my_script.src='http://{{ host }}/booky.js?x='+(Math.random());
        iFD.contentDocument.getElementsByTagName('head')[0].appendChild(my_script);
      }
      else {
        // Use timeout as opposed to a while loop so we return control to the
        // render thread.
        setTimeout(pollFrameReady, 30)
      }
    })()
  }

  $(function() {
    iFD = document.getElementById('link_selection_frame');
    $('#link_selection_url').data('pre','http://');
    $('#link_selection_url').on('keyup', function(e) {
      if(this.value.indexOf('http://') == 0) {
        $(this).data('pre','http://');
        this.value = this.value.substr(7);
        $('.add-on').text('http://');
      } else if(this.value.indexOf('https://') == 0) {
        $(this).data('pre','https://');
        this.value = this.value.substr(8);
        $('.add-on').text('https://');
      }
      if (e.keyCode == 13) pload($(this).data('pre')+this.value);
    })
  })
</script>
{% endblock %}

{% block content %}
<div class="hero-unit">
  <h1>Make the web come to you</h1>

  <p>Turn any website into a periodic email digest.</p>
  <p>
    To get started, either:
    <ul>
      <li>drag the following bookmarklet into your bookmark bar: <a href="javascript:(function(){my_script=document.createElement('script');my_script.type='text/javascript';my_script.src='http://{{ host }}/booky.js?x='+(Math.random());document.getElementsByTagName('head')[0].appendChild(my_script);})();" class="btn btn-primary">Digest this page</a></li>
      OR
      <li>type or paste the address into the box below and press enter (you can paste with or without the http(s) prefix)</li>
    </ul>
  </p>
  </form>
</div>

<!-- Example row of columns -->
<div class="input-prepend">
<span class="add-on">http://</span>
  <input type="text" id="link_selection_url" /></div> <span id="loading"></span>
<iframe id="link_selection_frame"> </iframe>
{% endblock %}

templates/digest/register.html
{% extends "digest/base.html" %}
{% block title %}Register{% endblock %}

{% block css %}
<style>
  label > span {
    display: inline-block;
    width: 130px;
  }
  .invalid {
    width: auto;
    color: red;
    margin-left: 1em;
  }
</style>
{% endblock %}

{% block js %}
<script>
  $(function() {
    // Run of the mill form validation, BS validates email
    $('#registration_form').submit(function(e) {
      $('.invalid').remove()

      var pass = $('#password').val(),
        passConf = $('#password_conf').val()

      if (!(pass == passConf)) {
        $('#password')
          .after('<span class="invalid">Passwords don\'t match</span>')
        e.preventDefault()
      }
    })
  })
</script>
{% endblock %}

{% block content %}
<h3>Register An Account</h3>
<hr>
<form action="/register/" method="post" id="registration_form">
  {% csrf_token %}
  <label><span>Email Address:</span>
    <input type="email" name="email" id="email_address" />
  </label>
  <label><span>Password:</span>
    <input type="password" name="password" id="password" />
  </label>
  <label><span>Password(confirm):</span>
    <input type="password" id="password_conf" />
  </label>
  <input type="submit" value="Register" class="btn btn-primary"/>
</form>
{% endblock %}